# Generated by Django 5.2.6 on 2025-09-29 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
