# Generated by Django 5.2.6 on 2025-10-01 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estudiante_fecha_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='universidad',
            field=models.CharField(choices=[('EPN', 'Escuela Politécnica Nacional (EPN)'), ('USFQ', 'Universidad San Francisco de Quito (USFQ)'), ('PUCE', 'Pontificia Universidad Católica del Ecuador (PUCE)'), ('UCE', 'Universidad Central del Ecuador (UCE)'), ('UDLA', 'Universidad de Las Américas (UDLA)'), ('UTE', 'Universidad Tecnológica Equinoccial (UTE)'), ('UISRAEL', 'Universidad Tecnológica Israel (UISRAEL)'), ('UNIVERSIDAD_DEL_QUINDIO', 'Universidad del Quindío'), ('UNIVERSIDAD_INTERNACIONAL_SEK', 'Universidad Internacional SEK'), ('OTRA', 'Otra universidad')], default='OTRA', max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
