# Generated by Django 5.2.6 on 2025-10-01 01:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_estudiante_universidad_estudiante_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve descripción sobre ti', max_length=500),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='es_vendedor_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +593XXXXXXXXX', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='El número debe estar en formato: +593XXXXXXXXX. (9-10 dígitos después del código país)', regex='^\\+593\\d{8,9}$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apodo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='universidad',
            field=models.CharField(choices=[('EPN', 'Escuela Politécnica Nacional (EPN)'), ('USFQ', 'Universidad San Francisco de Quito (USFQ)'), ('PUCE', 'Pontificia Universidad Católica del Ecuador (PUCE)'), ('UCE', 'Universidad Central del Ecuador (UCE)'), ('UDLA', 'Universidad de Las Américas (UDLA)'), ('UTE', 'Universidad Tecnológica Equinoccial (UTE)'), ('UISRAEL', 'Universidad Tecnológica Israel (UISRAEL)'), ('UNIVERSIDAD_DEL_QUINDIO', 'Universidad del Quindío'), ('UNIVERSIDAD_INTERNACIONAL_SEK', 'Universidad Internacional SEK'), ('OTRA', 'Otra universidad')], default='OTRA', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
