# Generated by Django 5.2.6 on 2025-10-01 01:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_fecha_registro'),
        ('usuarios', '0004_alter_estudiante_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('libros_texto', '📚 Libros de Texto'), ('apuntes_guias', '📝 Apuntes y Guías'), ('electronica', '💻 Electrónica'), ('instrumentos_laboratorio', '🔬 Instrumentos Lab'), ('ropa', '👕 Ropa'), ('deportes', '⚽ Deportes'), ('comida', '🍕 Comida'), ('accesorios', '🎒 Accesorios'), ('muebles_hogar', '🛋️ Muebles Hogar'), ('arte_musica', '🎨 Arte y Música'), ('servicios', '🛠️ Servicios'), ('otros', '📦 Otros')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='📦', max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='condicion',
            field=models.CharField(choices=[('nuevo', '🆕 Nuevo'), ('como_nuevo', '🌟 Como nuevo'), ('bueno', '👍 Bueno'), ('regular', '✅ Regular'), ('necesita_reparacion', '🔧 Necesita reparación')], default='bueno', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', '🟢 Disponible'), ('vendido', '🔴 Vendido'), ('reservado', '🟡 Reservado'), ('inactivo', '⚫ Inactivo')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_envio',
            field=models.CharField(choices=[('recoger', '🏫 Recoger en universidad'), ('envio', '🚗 Envío a domicilio'), ('ambos', '📦 Ambos')], default='recoger', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default='Universidad Central del Ecuador', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_vendidos', to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.estudiante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_favoritos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-agregado_en'],
                'unique_together': {('estudiante', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'ordering': ['orden', 'creado_en'],
            },
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
