# Generated by Django 5.2.6 on 2025-10-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_remove_pedido_comprador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
    ]
