# Generated by Django 5.2.6 on 2025-11-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_envio',
            field=models.CharField(choices=[('recoger', '🏫 Recoger en universidad'), ('envio', '🚗 Envío a domicilio')], default='recoger', max_length=10),
        ),
    ]
